site_name: Let's Go! Golang 短视频教程
theme: readthedocs
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True  #for use of inline $..$

pages:
    - 简介: 'index.md'
